-- ================================================================
-- Mesa Group Consulting - Vector Search Migration
-- ================================================================
-- Purpose: Add vector search capability to project_knowledge table
-- Date: December 20, 2025
-- Based on: Legal Document AI vector architecture
-- ================================================================

-- Step 0: Create claude_memory schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS claude_memory;

-- Step 1: Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 1.5: Create project_knowledge table if it doesn't exist
CREATE TABLE IF NOT EXISTS claude_memory.project_knowledge (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  key text NOT NULL,
  value text NOT NULL,
  context text,
  source text,
  confidence numeric DEFAULT 1.0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(category, key)
);

-- Add comment on table
COMMENT ON TABLE claude_memory.project_knowledge IS
'Project knowledge base for Claude memory system. Stores key-value pairs with semantic search capability.';

-- Step 2: Add embedding column to project_knowledge table
ALTER TABLE claude_memory.project_knowledge
ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Add comment explaining the column
COMMENT ON COLUMN claude_memory.project_knowledge.embedding IS
'Vector embedding generated by OpenAI text-embedding-3-small (1536 dimensions) for semantic search';

-- Step 3: Create vector similarity search function
CREATE OR REPLACE FUNCTION claude_memory.search_knowledge_semantic(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 10
)
RETURNS TABLE (
  category text,
  key text,
  value text,
  context text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    pk.category,
    pk.key,
    pk.value,
    pk.context,
    1 - (pk.embedding <=> query_embedding) as similarity
  FROM claude_memory.project_knowledge pk
  WHERE pk.embedding IS NOT NULL
    AND 1 - (pk.embedding <=> query_embedding) > match_threshold
  ORDER BY pk.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION claude_memory.search_knowledge_semantic IS
'Semantic search function using cosine similarity. Returns top matches above threshold.';

-- Step 4: Create hybrid search function (vector + keyword filter)
CREATE OR REPLACE FUNCTION claude_memory.search_knowledge_hybrid(
  query_embedding vector(1536),
  filter_category text DEFAULT NULL,
  match_threshold float DEFAULT 0.5,
  match_count int DEFAULT 10
)
RETURNS TABLE (
  category text,
  key text,
  value text,
  context text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  IF filter_category IS NULL THEN
    -- No category filter, pure vector search
    RETURN QUERY
    SELECT * FROM claude_memory.search_knowledge_semantic(
      query_embedding,
      match_threshold,
      match_count
    );
  ELSE
    -- Hybrid: vector search + category filter
    RETURN QUERY
    SELECT
      pk.category,
      pk.key,
      pk.value,
      pk.context,
      1 - (pk.embedding <=> query_embedding) as similarity
    FROM claude_memory.project_knowledge pk
    WHERE pk.embedding IS NOT NULL
      AND pk.category = filter_category
      AND 1 - (pk.embedding <=> query_embedding) > match_threshold
    ORDER BY pk.embedding <=> query_embedding
    LIMIT match_count;
  END IF;
END;
$$;

COMMENT ON FUNCTION claude_memory.search_knowledge_hybrid IS
'Hybrid search combining vector similarity with optional category filtering.';

-- Step 5: Create search by text function (generates embedding and searches)
-- Note: This function signature is for documentation only
-- Actual embedding generation will be done via OpenAI API in Node.js script
COMMENT ON FUNCTION claude_memory.search_knowledge_semantic IS
'To search by text:
1. Generate embedding using OpenAI API (text-embedding-3-small)
2. Call: SELECT * FROM claude_memory.search_knowledge_semantic(embedding, 0.5, 10)
See embedding generation script for implementation.';

-- Step 6: Create vector index for fast similarity search
-- Using IVFFlat index for performance (Supabase default)
CREATE INDEX IF NOT EXISTS project_knowledge_embedding_idx
ON claude_memory.project_knowledge
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

COMMENT ON INDEX claude_memory.project_knowledge_embedding_idx IS
'IVFFlat index for fast cosine similarity search. Lists=100 optimized for ~10K vectors.';

-- Step 7: Create helper view for search results with metadata
CREATE OR REPLACE VIEW claude_memory.search_results_enriched AS
SELECT
  pk.id,
  pk.category,
  pk.key,
  pk.value,
  pk.context,
  pk.source,
  pk.confidence,
  pk.created_at,
  pk.updated_at,
  -- Helper columns for debugging
  CASE
    WHEN pk.embedding IS NULL THEN 'No embedding'
    ELSE 'Has embedding'
  END as embedding_status,
  1536 as embedding_dimensions
FROM claude_memory.project_knowledge pk;

COMMENT ON VIEW claude_memory.search_results_enriched IS
'Enriched view for debugging search results and checking embedding status.';

-- ================================================================
-- VERIFICATION QUERIES
-- ================================================================

-- Check if vector extension is enabled
SELECT * FROM pg_extension WHERE extname = 'vector';

-- Check embedding column exists
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'claude_memory'
  AND table_name = 'project_knowledge'
  AND column_name = 'embedding';

-- Check how many rows have embeddings
SELECT
  COUNT(*) as total_rows,
  COUNT(embedding) as rows_with_embeddings,
  COUNT(*) - COUNT(embedding) as rows_without_embeddings
FROM claude_memory.project_knowledge;

-- Check index exists
SELECT indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'claude_memory'
  AND tablename = 'project_knowledge'
  AND indexname = 'project_knowledge_embedding_idx';

-- ================================================================
-- SUCCESS MESSAGE
-- ================================================================

DO $$
BEGIN
  RAISE NOTICE '✅ Vector search migration completed successfully!';
  RAISE NOTICE '';
  RAISE NOTICE 'Next steps:';
  RAISE NOTICE '1. Run embedding generation script to populate embeddings';
  RAISE NOTICE '2. Test semantic search with: SELECT * FROM claude_memory.search_knowledge_semantic(embedding, 0.5, 10)';
  RAISE NOTICE '3. See SUPABASE-MEMORY-QUICK-REFERENCE.md for usage examples';
END $$;
